lst = list('0123456789abcdef')
with open('allhex.txt','a') as db:
    for hex1 in lst:
        for hex2 in lst:
            for hex3 in lst:
                for hex4 in lst:
                    for hex5 in lst:
                        for hex6 in lst:
                            for hex7 in lst:
                                for hex8 in lst:
                                    for hex9 in lst:
                                        for hex10 in lst:
                                            for hex11 in lst:
                                                for hex12 in lst:
                                                    for hex1 in lst:
                                                        for hex13 in lst:
                                                            for hex14 in lst:
                                                                for hex15 in lst:
                                                                    for hex16 in lst:
                                                                        for hex17 in lst:
                                                                            for hex18 in lst:
                                                                                for hex19 in lst:
                                                                                    for hex20 in lst:
                                                                                        for hex21 in lst:
                                                                                            for hex22 in lst:
                                                                                                for hex23 in lst:
                                                                                                    for hex24 in lst:
                                                                                                        for hex25 in lst:
                                                                                                            for hex26 in lst:
                                                                                                                for hex27 in lst:
                                                                                                                    for hex28 in lst:
                                                                                                                        for hex29 in lst:
                                                                                                                            for hex30 in lst:
                                                                                                                                for hex31 in lst:
                                                                                                                                    for hex32 in lst:
                                                                                                                                        for hex33 in lst:
                                                                                                                                            for hex34 in lst:
                                                                                                                                                for hex35 in lst:
                                                                                                                                                    for hex36 in lst:
                                                                                                                                                        for hex37 in lst:
                                                                                                                                                            for hex38 in lst:
                                                                                                                                                                for hex39 in lst:
                                                                                                                                                                    for hex40 in lst:
                                                                                                                                                                        for hex41 in lst:
                                                                                                                                                                            for hex42 in lst:
                                                                                                                                                                                for hex43 in lst:
                                                                                                                                                                                    for hex44 in lst:
                                                                                                                                                                                        for hex45 in lst:
                                                                                                                                                                                            for hex46 in lst:
                                                                                                                                                                                                for hex47 in lst:
                                                                                                                                                                                                    for hex48 in lst:
                                                                                                                                                                                                        for hex49 in lst:
                                                                                                                                                                                                            for hex50 in lst:
                                                                                                                                                                                                                for hex51 in lst:
                                                                                                                                                                                                                    for hex52 in lst:
                                                                                                                                                                                                                        for hex53 in lst:
                                                                                                                                                                                                                            for hex54 in lst:
                                                                                                                                                                                                                                for hex55 in lst:
                                                                                                                                                                                                                                    for hex56 in lst:
                                                                                                                                                                                                                                        for hex57 in lst:
                                                                                                                                                                                                                                            for hex58 in lst:
                                                                                                                                                                                                                                                for hex59 in lst:
                                                                                                                                                                                                                                                    for hex60 in lst:
                                                                                                                                                                                                                                                        for hex62 in lst:
                                                                                                                                                                                                                                                            for hex63 in lst:
                                                                                                                                                                                                                                                                for hex64 in lst:
                                                                                                                                                                                                                                                                    db.write(hex1+hex2+hex3+hex4+hex5+hex6+hex7+hex8+hex9+hex10+hex11+hex12+hex13+hex14+hex15+hex16+hex17+hex18+hex19+hex20+hex21+hex22+hex23+hex24+hex25+hex26+hex27+hex28+hex29+hex30+hex31+hex32+hex33+hex34+hex35+hex36+hex37+hex38+hex39+hex40+hex41+hex42+hex43+hex44+hex45+hex46+hex47+hex48+hex49+hex50+hex51+hex52+hex53+hex54+hex55+hex56+hex57+hex58+hex59+hex60+hex61+hex62+hex63+hex64+'\n')